name: sdg-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - attrs
  - blinker
  - branca
  - cachetools
  - certifi
  - charset-normalizer
  - click
  - folium
  - geopandas
  - gitdb
  - gitpython
  - idna
  - jinja2
  - jsonschema
  - jsonschema-specifications
  - markdown-it-py
  - markupsafe
  - mdurl
  - narwhals
  - numpy
  - packaging
  - pandas
  - pillow
  - plotly
  - protobuf
  - psycopg2-binary
  - pyarrow
  - pydeck
  - pygments
  - pyogrio
  - pyproj
  - python-dateutil
  - python-dotenv
  - pytz
  - referencing
  - requests
  - rich
  - rpds-py
  - shapely
  - six
  - smmap
  - sqlalchemy
  - streamlit
  - streamlit-folium
  - tenacity
  - toml
  - tornado
  - typing-extensions
  - tzdata
  - urllib3
  - watchdog
  - xyzservices
